### PR TITLE
Update version to HEAD / 1.3.0.pre, build against Arrow 0.6.0 final

### PR DESCRIPTION
**Pull request by wesm**
see also https://github.com/conda-forge/arrow-cpp-feedstock/pull/36

### CODE REVIEW

**Comment by wesm** [comment]
Rebased and awaiting build now that Arrow 0.6.0 packages are posted

**Comment by xhochy** [comment]
@wesm was the some API breakage in Arrow 0.6.0 so that we need a new parquet-cpp release?

**Comment by wesm** [comment]
Well, the problem is that `pyarrow=0.5.*` is pinned to parquet-cpp 1.2.x, so if we push a new build (to account for ABI change in pyarrow) then installations of `pyarrow=0.5.0` will be broken. We can call the release "1.3.0.pre" but use exactly parquet-cpp 1.2.0 tag which would have the same effect

**Comment by xhochy** [comment]
Ah, that makes sense. Still, I have the feeling we should separate `pyarrow.parquet` in a bit more far future into its own package to break this cycle. At the moment, I wouldn't do it and wait how well things work with Ray and turbodbc packaging

**Review by xhochy — APPROVED** [review]

**Comment by wesm** [comment]
I'm not sure how that separation would help, since we still have dependence on the Arrow ABI. Realistically when Arrow releases, at least for the next 6-12 months, downstream users will have to upgrade if they are using conda-forge or PyPI for packaging. Or we can get ourselves into the multi-ABI business that NumPy has been in for a while. This is the price of progress (having to keep up with Arrow releases), and I think it's worth paying

I'm all for establishing some level of ABI compatibility, but there needs to be a lot more active C++ developers for that to happen. It would be too burdensome given our current resouces

**Pull request merged**
