### PR TITLE
update to latest

### PR DESCRIPTION
**Pull request by leifwalsh**

### CODE REVIEW

**Comment by wesm** [comment]
The OS X artifact for arrow-cpp 0.2 hasn't landed yet, so the OS X build here will fail https://anaconda.org/conda-forge/arrow-cpp/files

**Comment by wesm** [comment]
Actually, I'm not sure. There were some ABI changes so it's possible that the previous arrow-cpp artifact available is ABI compatible

**Comment by leifwalsh** [comment]
Oops. It will fail because I added a version restriction. Sorry. Should I close this?

**Comment by leifwalsh** [comment]
Oh neat I guess we got lucky.

**Comment by leifwalsh** [comment]
@wesm good to go now.

**Pull request merged**
