### PR TITLE
Update boost pin

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jschueller** [comment]
@conda-forge-admin, please rerender

**Review by xhochy — APPROVED** [review]

**Comment by xhochy** [comment]
@MaxRis Is this the same failure we were seeing in Arrow before?

**Comment by maxhora** [comment]
@xhochy yes, it should be it, since [-DBOOST_ALL_NO_LIB](https://github.com/apache/parquet-cpp/blob/master/cmake_modules/ThirdpartyToolchain.cmake#L70)  is not defined for static boost libs linkage. I can patch it as well.

**Comment by xhochy** [comment]
@MaxRis as always this would be very much appreciated.

**Comment by maxhora** [comment]
@xhochy have created PR with patch https://github.com/jschueller/parquet-cpp-feedstock/pull/1
Build passed there https://ci.appveyor.com/project/MaxRisuhin/parquet-cpp-feedstock/build/1.0.12
thanks!

**Pull request merged**
